name: Build
on:
  push:
    branches:
     - 'main'
     - 'cicd'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build application in Docker builder stage
      uses: shrink/actions-docker-extract@v1
      with:
        push: false
        target: builder